name: Release
on:
  push:
    branches: [ $default-branch ]
    tags:
      - "*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Rust environment
      uses: ATiltedTree/setup-rust@v1.0.4      
      with:
        rust-version: stable
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 17.x
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target
        key: ${{ runner.os }}-cargo
      
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install Dependencies
      run: pnpm install
      
    - name: Build Front-End
      run: pnpm build
      
    - name: Build 
      run: pnpm tauri build
      
    - name: Read Utility Version
      run: echo "VERSION=$(cat src-tauri/tauri.conf.json | grep version | head -n1 | awk '{ print substr($2, 2, length($2)-2) }')" >> $GITHUB_ENV
    
    - name: Move DMG Image
      run: mv "./src-tauri/target/release/bundle/dmg/Tongfang Utility_"$VERSION"_x64.dmg"  "./Tongfang-Utility-macOS.dmg"
    
    - name: Move DMG Image
      run: mv "./src-tauri/target/release/bundle/macos/Tongfang Utility.app.tar.gz"  "./Tongfang-Utility-macOS-update.app.tar.gz"
      
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        token: ${{ secrets.token }}
        
    - name: Upload Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: Tongfang-Utility-macOS.dmg
        asset_path: ./Tongfang-Utility-macOS.dmg
        asset_content_type: application/octet-stream
        
    - name: Upload Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: Tongfang-Utility-macOS-update.app.tar.gz
        asset_path: ./Tongfang-Utility-macOS-update.app.tar.gz
        asset_content_type: application/gzip        
